---
- name: Un-deploy Webserver
  hosts: webservers
  become: yes
  tasks:
    - name: Stop and disable Nginx service
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: no
    - name: Remove Nginx
      ansible.builtin.package:
        name: nginx
        state: absent
    - name: Remove index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
